production:
  adapter: postgresql
  encoding: unicode
  database: 3lion_kennel24
  pool: 5
  host: postgresql0.locum.ru
  username: 3lion_kennel24
  password: AxHE9qyN

development:
  adapter: postgresql
  encoding: unicode
  database: kennel_development
  pool: 5
  username: postgres
  password: qweqwe

test:
  adapter: postgresql
  encoding: unicode
  database: kennel_test
  pool: 5
  username: postgres
  password: qweqwe

